### PR TITLE
Add rule.AttrAssignExpr function

### LINKED ISSUE #1389: Rule API: can't access the assigment statements
The rule.Rule API stores a map of `*bzl.AssignExpr` but you can't get the actual expr.  This means you can't read or write the comments there, which is a common place for users to put comments.

### PR DESCRIPTION
**Pull request by pcj**
**What type of PR is this?**

> Feature

**What package or component does this PR mostly affect?**

> all

**What does this PR do? Why is it needed?**

Allows programmatic access to the assignment expressions of a rule.

**Which issues(s) does this PR fix?**

Fixes #1389

### CODE REVIEW

**Comment by achew22** [comment]
Seems like a reasonable path forward. Could you explain why defining directives as a part of your plugin doesn't achieve what you want? Maybe there is a control surface that we should be adding to Gazelle instead of pushing the complexity on plugin implementors

**Comment by pcj** [comment]
@achew22 directives are fine way of reading configuration data from users in the build file.  

However, if plugin authors want to add comments to generated rules, they have limited options: Use the `rule.AddComment()` API, which makes it really hard to avoid duplicate comments when the rule already exists, or put it on the LHS of the assigment, which is where nobody ever actually writes comments.

**Comment by pcj** [comment]
I could entertain a different function `rule.AttrComments(name string) *bzl.Comments` if that sounds better.

**Comment by pcj** [comment]
Closing in favor of https://github.com/bazelbuild/bazel-gazelle/pull/1394.

**Pull request closed without merging**
