### PR TITLE
fix: patch support for dir named workspace

### PR DESCRIPTION
**Pull request by michaellzc**
**What type of PR is this?**

Bug fix

**What package or component does this PR mostly affect?**

all

**What does this PR do? Why is it needed?**

fix https://github.com/bazelbuild/bazel-gazelle/pull/1498 to actually support dir named `workspace`

**Notes**

Upon upgrading to the latest gazelle that includes https://github.com/bazelbuild/bazel-gazelle/pull/1498, we're still seeing

```
gazelle: read /private/var/tmp/_bazel_michael/ddd60c3e827a4aa3b925c14f76ccd5bf/external/com_github_sourcegraph_controller_cdktf_gen_tfe/WORKSPACE: is a directory
```

In https://github.com/bazelbuild/bazel-gazelle/pull/1498, we missed that the `FindWORKSPACEFile` will return `/some/path/WORKSPACE` regardless if one can be found. See the final `return` statement.

https://github.com/bazelbuild/bazel-gazelle/blob/adce430fa38848f0b3805e05f9520e419a41dfd7/internal/wspace/finder.go#L38-L46

hence when we attempt to `rule.LoadWorkspaceFile`, we end up getting a `is a directory` error from `os.ReadFile`

this PR added handling on error return from `LoadWorkspaceFile` to ignore `IsDir` error as well.

https://github.com/michaellzc/bazel-gazelle/blob/86a4c72015d911a3bbe18ad57d473684300d8f1c/cmd/gazelle/fix-update.go#L143-L154

tested locally in a project:

```
| tfe/
| go.mod
| - workspace/
|   - workspace.go
```

```
$ gazelle fix -go_prefix somerpefx -repo_root .
# confirmed BUILD file is generated
$ cat workspace/BUILD.bazel
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    # ...
)
```

### CODE REVIEW

**Comment by michaellzc** [comment]
CLA has been signed

**Comment by alexeagle** [comment]
LGTM

**Review by jbedard — APPROVED** [review]
👍

**Review by fmeum — APPROVED** [review]
It looks like this should also work on Windows. Thanks for sending the fix!

**Pull request merged**
