### PR TITLE
Add rule.AttrComments func

### LINKED ISSUE #1389: Rule API: can't access the assigment statements
The rule.Rule API stores a map of `*bzl.AssignExpr` but you can't get the actual expr.  This means you can't read or write the comments there, which is a common place for users to put comments.

### PR DESCRIPTION
**Pull request by pcj**
**What type of PR is this?**

> Feature

**What package or component does this PR mostly affect?**

> all

**What does this PR do? Why is it needed?**

Allows programmatic access to the assignment expression comments.

**Which issues(s) does this PR fix?**

Fixes #1389

### CODE REVIEW

**Comment by achew22** [comment]
@pcj I think this is a lot more in line with what I would have expected. That said, it still has us exporting a non-primitive type from another package into our public API. Not asking you to do any code writing on this front, but curious about a couple of things.

* Is this a situation where we'd benefit from a `rule.AddComment` method? To me that seems even more discoverable as an API surface than `AttrComments`?
* Do you have more precise manipulation you're looking for here? Do you have maybe an example of the before/after that you're looking to get?

**Comment by kusaeva** [comment]
Hi @pcj!
Could you please rebase the PR to make a patch applicable for the latest version of bazel-gazelle?

**Comment by fmeum** [comment]
This was done in #1700

**Comment by pcj** [comment]
Glad to see this was finally merged, thanks.

**Pull request closed without merging**
