### PR TITLE
Merge the private attribute

### PR DESCRIPTION
**Pull request by alexeagle**
**What type of PR is this?**

Bug fix

**What package or component does this PR mostly affect?**

cmd/gazelle

**What does this PR do? Why is it needed?**

Currently the `private` attribute isn't copied.

**Which issues(s) does this PR fix?**

Fixes #

**Other notes for review**

### CODE REVIEW

**Comment by alexeagle** [comment]
/fyi @f0rmiga I'll need some help here filling in the template, I'm not sure how this bug manifests. The test failure it fixes isn't very clear what `private` is.

**Comment by achew22** [comment]
I'm also a little confused about what this is fixing. Is there any way we could pull together a quick testcase of this so we don't regress in the future?

**Comment by f0rmiga** [comment]
We are currently using a private attribute to assign a UUID to the `py_library` target. Any `py_test` and `py_binary` in the same Bazel package will then "import" this UUID, which gets resolved later in the `Resolve` method.

The private attribute gets passed around when it's first generated but on subsequent runs, after the target is already generated, the private attributes are purged. This patch allows the private attributes to stay in the targets during the resolution stage.

**Comment by achew22** [comment]
Generally speaking I prefer to have some level of testing to prevent regressions. Could we add a test to prevent this backsliding?

**Comment by f0rmiga** [comment]
@achew22 any chance we could have this so we don't need to patch Gazelle from rules_python?

**Pull request merged**
