### PR TITLE
Exporting ProtoConfig.StripImportPrefix and ProtoConfig.ImportPrefix

### PR DESCRIPTION
**Pull request by ekleiner**

### CODE REVIEW

**Comment by ekleiner** [comment]
@googlebot I signed it!

**Comment by ekleiner** [comment]
I am implementing an extension. which generates proto_library and need this configs: https://github.com/bazelbuild/bazel-gazelle/issues/727#issuecomment-597656554

**Comment by ekleiner** [comment]
https://github.com/bazelbuild/bazel-gazelle/issues/727#issuecomment-598970652

**Comment by ekleiner** [comment]
I am implementing an extension which generates proto_library and need  ProtoConfig.StripImportPrefix and ProtoConfig.ImportPrefix. See
https://github.com/bazelbuild/bazel-gazelle/issues/727#issuecomment-597656554

**Comment by linzhp** [comment]
We are generating proto_library separately, but we want to reuse `language/proto.Config`

**Comment by ekleiner** [comment]
I use language/proto.Config directly. Getting it by https://github.com/bazelbuild/bazel-gazelle/blob/master/language/proto/config.go#L64

**Pull request merged**
