### PR TITLE
Make attribute value sorting configurable

### PR DESCRIPTION
**Pull request by t-8ch**
**What type of PR is this?**

Feature

**What package or component does this PR mostly affect?**

rule

**What does this PR do? Why is it needed?**

The existing hardcoded sorting logic can get in the way. Provide a mechanism for users to opt-in or opt-out of it.
The default behavior is unchanged.

### CODE REVIEW

**Review by fmeum — APPROVED** [review]
Thanks, I like how this makes `UnsortedStrings` less of a special case.

**Comment by t-8ch** [comment]
We are using a custom struct that handles combinations of lists of plain strings and `select()`s and that implements `BzlExprValue`.

If no `select()`s are present and only strings are emitted, the default sorting logic of gazelle kicks in, which is undesirable.
Instead of having to add a new step that detects this case and emits now an `UnsortedStrings` it is easier with this interface.

**Comment by fmeum** [comment]
Hmm, to me this sounds as if this isn't really about the type of the attribute value but really about the name of the attribute. Could we instead just make the set of attributes to sort configurable on the rule?

**Comment by t-8ch** [comment]
That would be fine, too.
I only need a way to disable the sorting, and I wanted to keep it close to the current `UnsortedStrings` mechanism.

**Comment by t-8ch** [comment]
I'm also a bit confused about the need for a custom sorting logic in gazelle in general.
Everything will go through buildifier anyways and that will just apply its own logic.

**Comment by fmeum** [comment]
Let's go with https://github.com/bazelbuild/bazel-gazelle/pull/1719 instead.

**Pull request closed without merging**
