### PR TITLE
[Gazelle] Fix Duplicate Load Bug

### PR DESCRIPTION
**Pull request by ckilian867**
If two extensions both import Kinds from the same file, and no load statement for those Kinds is already in the BUILD.bazel file, then Gazelle will add the load statement twice.

In this commit, we fix the issue by updating the tracked loads when a new load is inserted into the index. This will cause future iterations to update the existing load instead of creating a duplicate.

**What type of PR is this?**

> Uncomment one line below and remove others.
>
Bug fix

**What package or component does this PR mostly affect?**

cmd/gazelle

**What does this PR do? Why is it needed?**

This PR fixes a bug where is two extensions each load a statement from the same file, and the file has no load statements at all, duplicate load statements will be added to the top of the file.

**Which issues(s) does this PR fix?**

None, its a small bug fix and the above directions say one isn't needed.

**Other notes for review**

None

### CODE REVIEW

**Review by tyler-french — APPROVED** [review]

**Comment by fmeum** [comment]
@ckilian867 The CI failures is a flake, but you still need to sign the CLA.

**Comment by ckilian867** [comment]
> @ckilian867 The CI failures is a flake, but you still need to sign the CLA.

I'm working with our OSS team to get this resolved

**Comment by fmeum** [comment]
Thanks, just ping me when it's done.

**Comment by ckilian867** [comment]
@fmeum Check is passing now

**Pull request merged**
