### PR TITLE
Respect .bazelignore [WIP]

### PR DESCRIPTION
**Pull request by Michaelhobo**

### CODE REVIEW

**Comment by Michaelhobo** [comment]
I may have sent this out prematurely, sorry for the spam. I'll close this for now and reopen when it's ready.

**Comment by vale1410** [comment]
@Michaelhobo  are you still planning to complete the merge request? Gazelle is still ignoring the .bazelignore file and this  is an issue for our monorepo with some few projects that are not built with bazel. Thanks in advance !

**Comment by Michaelhobo** [comment]
@vale1410 I had trouble building gazelle to test this change, and I put it aside for a while. It's probably better to jump on https://github.com/bazelbuild/bazel-gazelle/issues/318
I'll take a look again, but I'm still trying to fix my build environment.

**Comment by Michaelhobo** [comment]
> @vale1410 I had trouble building gazelle to test this change, and I put it aside for a while. It's probably better to jump on #318
> I'll take a look again, but I'm still trying to fix my build environment.

I got things working, and it's out for review in #1022

**Pull request closed without merging**
