### PR TITLE
rule: make value sorting configurable (alternative implementation)

### PR DESCRIPTION
**Pull request by t-8ch**
**What type of PR is this?**

> Feature

**What package or component does this PR mostly affect?**

rule

**What does this PR do? Why is it needed?**

Alternative to #1713

### CODE REVIEW

**Review by fmeum — APPROVED** [review]
Nice, this looks much cleaner!

@tyler-french Could you also take a look?

**Comment by t-8ch** [comment]
Friendly ping @tyler-french .

I won't work on my current project for much longer and I'd like to hand it having to use my personal fork of gazelle.

**Comment by tyler-french** [comment]
Got it. Will try to get this tested and reviewed today

**Comment by t-8ch** [comment]
Thanks a lot!

**Review by tyler-french — APPROVED** [review]
Looks good to me. I also tested this in Uber's Go Monorepo.

**Review by fmeum — APPROVED** [review]

**Pull request merged**
