### PR TITLE
fileinfo: fix not detecting 'unix' files to be OS specific

### PR DESCRIPTION
**Pull request by sluongng**
The build file generation logic works like this today:

```
GenerateRules()
  package.go->*goTarget.addFiles
  package.go->getPlatformStringsAddFunction()
  fileinfo.go->isOSArchSpecific()
```

Depending on whether the file has special Go build directives, Gazelle
would use a different logic to include/exclude the file into the 'srcs'
attribute of the Go targets.

In #1512, we added support for 'unix' build directive but did not tell
Gazelle to treat files with 'unix' file as OS specific file. This caused
Gazelle to mismatch the OS in a later stage and exclude the needed file
instead.

Fix that logic and provide some additional tests to reinforce the
fileinfo logic.

Also added a small knob to print stdout of Gazelle when it's run under
go_repository with `debug_mode` attribute set to True.  Most Gazelle's
logs are printed to stdout and not stderr.

**What type of PR is this?**

Bug fix

**What package or component does this PR mostly affect?**

language/go

go_repository

**What does this PR do? Why is it needed?**

**Which issues(s) does this PR fix?**

Replaces #1551

Fix #1512

**Other notes for review**

### CODE REVIEW

**Comment by sluongng** [comment]
cc @connyay @fmeum

**Review by fmeum — APPROVED** [review]
Great, thanks for the detective work!

**Comment by connyay** [comment]
👍 This patch is working for my usage - sorry for the fire drill!

**Review by tempoz — COMMENTED** [review]
LGTM, thanks for submitting that PR to gazelle!

**Comment by sluongng** [comment]
another ping to request for a minor release

**Comment by linzhp** [comment]
No objection for minor release, but this weekend is fully booked for me. Can @fmeum or @achew22 do it?

**Comment by linzhp** [comment]
Released: https://github.com/bazelbuild/bazel-gazelle/releases/tag/v0.31.1

**Pull request merged**
