### PR TITLE
Detect whether Gazelle itself is a Bazel module

### LINKED ISSUE #1621: Error running gazelle loaded in WORKSPACE mode with --enable_bzlmod repo
### What version of gazelle are you using?

`v0.32.0`

### What version of rules_go are you using?

`v0.41.0`

### What version of Bazel are you using?

```
❯ bazel version
Bazelisk version: development
Starting local Bazel server and connecting to it...
Build label: 6.3.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Aug 8 15:48:33 2023 (1691509713)
Build timestamp: 1691509713
Build timestamp as int: 1691509713
```

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux (Ubuntu 23.04) - x86_64

### What did you do?

I have a workspace configured with gazelle and recently I wanted to add rules_oci. I decided to try out bzlmod but only for rules_oci, our repo is large and I didn't want to change everything all at once (especially do not want to change rules_python as currently bzlmod mode is missing some features). So currently I have gazelle configured through the WORKSPACE but I have `--enable_bzlmod` set in my .bazelrc

The error goes away when I add a --noenable_bzlmod to override my .bazelrc file, so I imagine its related to bzlmod support. Not sure how well supported a mixed bzlmod/WORKSPACE repo is?

### What did you expect to see?

similar output to what I get when I do not enabled bzlmod

```
❯ bazel run --noenable_bzlmod //:gazelle -- -build_tags=unit,integration,fts5,json1
Starting local Bazel server and connecting to it...
INFO: Invocation ID: fd9d4ef0-ef7a-47c5-ab73-95bb2dc3a542
INFO: Analyzed target //:gazelle (151 packages loaded, 14841 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  /home/tony.kinsley/code/github.com/braincorp/titanium-bazel-build/bin/gazelle-runner.bash
  /home/tony.kinsley/code/github.com/braincorp/titanium-bazel-build/bin/gazelle
INFO: Elapsed time: 41.280s, Critical Path: 0.43s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: /home/tony.kinsley/code/github.com/braincorp/titanium-bazel-build/bin/gazelle '-build_tags=unit,integration,fts5,json1'
```

### What did you see instead?

```
❯ bazel run //:gazelle -- -build_tags=unit,integration,fts5,json1
INFO: Invocation ID: 3122ed09-d438-4570-8438-d31c1160af56
ERROR: /home/tony.kinsley/code/github.com/braincorp/titanium-bazel/BUILD.bazel:16:8: every rule of type _gazelle_runner implicitly depends upon the target '@bazel_gazelle_go_repository_config//:WORKSPACE', but this target could not be found because of: no such target '@bazel_gazelle_go_repository_config//:WORKSPACE': target 'WORKSPACE' not declared in package '' defined by /home/tony.kinsley/.cache/bazel/_bazel_tony.kinsley/5b466fe6d0bf121e0d4086ac6c4e9a68/external/bazel_gazelle_go_repository_config/BUILD.bazel; however, a source file of this name exists.  (Perhaps add 'exports_files(["WORKSPACE"])' to /BUILD?)
ERROR: Analysis of target '//:gazelle' failed; build aborted:
INFO: Elapsed time: 0.975s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 270 targets configured)
ERROR: Build failed. Not running target
```

@fmeum as discussed https://bazelbuild.slack.com/archives/C01HMGN77Q8/p1693261283252459

### PR DESCRIPTION
**Pull request by fmeum**
**What type of PR is this?**

Bug fix

**What package or component does this PR mostly affect?**

cmd/gazelle

**What does this PR do? Why is it needed?**

Previously, we gated certain Bzlmod-specific behavior behind a general check for `--enable_bzlmod`, but even with that flag, Gazelle may still be a regular WORKSPACE dependency.

**Which issues(s) does this PR fix?**

Fixes #1621

**Other notes for review**

### CODE REVIEW

**Comment by fmeum** [comment]
@tkinz27 @tyler-french Could you test this?

**Comment by tkinz27** [comment]
I'm currently getting the following errors both with --enable_bzlmod (set in .bazelrc) and --noenable_bzlmod (explicitly set on cli)

```sh
~/code/github.com/braincorp/titanium-bazel rules_oci* ⇣⇡
❯ bazel run --noenable_bzlmod //:gazelle -- -build_tags=unit,integration,fts5,json1
Starting local Bazel server and connecting to it...
INFO: Invocation ID: b1bd43f1-9216-4656-8c10-dec9eb1b0e36
DEBUG: Rule 'bazel_gazelle' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c3323a4a7aed0427bae556d1953bb7852b3e0bcd755dc2f62229bf9b83bedf89"
DEBUG: Repository bazel_gazelle instantiated at:
  /home/tony.kinsley/code/github.com/braincorp/titanium-bazel/WORKSPACE:29:13: in <toplevel>
Repository rule http_archive defined at:
  /home/tony.kinsley/.cache/bazel/_bazel_tony.kinsley/5b466fe6d0bf121e0d4086ac6c4e9a68/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: Error computing the main repository mapping: Every .bzl file must have a corresponding package, but '@bazel_gazelle//:deps.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
Loading:

~/code/github.com/braincorp/titanium-bazel rules_oci* ⇣⇡
❯ bazel run //:gazelle -- -build_tags=unit,integration,fts5,json1                                         
INFO: Invocation ID: 324a32e3-1a12-43ca-b2de-8c97d1c32c65
DEBUG: Rule 'bazel_gazelle' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c3323a4a7aed0427bae556d1953bb7852b3e0bcd755dc2f62229bf9b83bedf89"
DEBUG: Repository bazel_gazelle instantiated at:
  /home/tony.kinsley/code/github.com/braincorp/titanium-bazel/WORKSPACE:29:13: in <toplevel>
Repository rule http_archive defined at:
  /home/tony.kinsley/.cache/bazel/_bazel_tony.kinsley/5b466fe6d0bf121e0d4086ac6c4e9a68/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: Error computing the main repository mapping: Every .bzl file must have a corresponding package, but '@bazel_gazelle//:deps.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
Loading:

~/code/github.com/braincorp/titanium-bazel rules_oci* ⇣⇡ 6s
❯ git diff
  diff --git a/WORKSPACE b/WORKSPACE
  index 90449979f5..b8f67c18d3 100644
  --- a/WORKSPACE
  +++ b/WORKSPACE
  @@ -28,10 +28,11 @@ http_archive(

   http_archive(
       name = "bazel_gazelle",
  -    sha256 = "29218f8e0cebe583643cbf93cae6f971be8a2484cdcfa1e45057658df8d54002",
  +    # sha256 = "29218f8e0cebe583643cbf93cae6f971be8a2484cdcfa1e45057658df8d54002",
       urls = [
  -        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.32.0/bazel-gazelle-v0.32.0.tar.gz",
  -        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.32.0/bazel-gazelle-v0.32.0.tar.gz",
  +        "https://github.com/bazelbuild/bazel-gazelle/archive/21b6fdb668c574cff1789ffd6b255728e22d43f7.tar.gz",
  +        # "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.32.0/bazel-gazelle-v0.32.0.tar.gz",
  +        # "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.32.0/bazel-gazelle-v0.32.0.tar.gz",
       ],
   )
```

Here is the relevant part of my WORKSPACE file

```starlark
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "278b7ff5a826f3dc10f04feaf0b70d48b68748ccd512d7f98bf442077f043fe3",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.41.0/rules_go-v0.41.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.41.0/rules_go-v0.41.0.zip",
    ],
)

http_archive(
    name = "bazel_gazelle",
    # sha256 = "29218f8e0cebe583643cbf93cae6f971be8a2484cdcfa1e45057658df8d54002",
    urls = [
        "https://github.com/bazelbuild/bazel-gazelle/archive/21b6fdb668c574cff1789ffd6b255728e22d43f7.tar.gz",
        # "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.32.0/bazel-gazelle-v0.32.0.tar.gz",
        # "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.32.0/bazel-gazelle-v0.32.0.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(
    nogo = "@//:nogo",
    version = "1.20",
)

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()
```

**Comment by fmeum** [comment]
@tkinz27 `strip_prefix = "bazel-gazelle-<commit hash>` is missing.

**Comment by tkinz27** [comment]
:man_facepalming:  sorry about that....

LGTM

```
~/code/github.com/braincorp/titanium-bazel rules_oci* ⇣⇡ 7s
❯ bazel run //:gazelle -- -build_tags=unit,integration,fts5,json1
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 47ce7403-38a9-4104-8eba-b938476abe7a
INFO: Analyzed target //:gazelle (182 packages loaded, 15774 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  /home/tony.kinsley/code/github.com/braincorp/titanium-bazel-build/bin/gazelle-runner.bash
  /home/tony.kinsley/code/github.com/braincorp/titanium-bazel-build/bin/gazelle
INFO: Elapsed time: 12.959s, Critical Path: 0.59s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: /home/tony.kinsley/code/github.com/braincorp/titanium-bazel-build/bin/gazelle '-build_tags=unit,integration,fts5,json1'
gazelle: /home/tony.kinsley/code/github.com/braincorp/titanium-bazel/src/python/BUILD.bazel: unknown directive: gazelle:python_root
gazelle: /home/tony.kinsley/code/github.com/braincorp/titanium-bazel/vendor/github.com/apache/arrow/go/v11/arrow/memory/internal/cgoalloc/allocator.go: error reading go file: /home/tony.kinsley/code/github.com/braincorp/titanium-bazel/vendor/github.com/apache/arrow/go/v11/arrow/memory/internal/cgoalloc/allocator.go: pkg-config not supported: #cgo !windows pkg-config: arrow
gazelle: /home/tony.kinsley/code/github.com/braincorp/titanium-bazel/vendor/github.com/apache/arrow/go/v12/arrow/memory/internal/cgoalloc/allocator.go: error reading go file: /home/tony.kinsley/code/github.com/braincorp/titanium-bazel/vendor/github.com/apache/arrow/go/v12/arrow/memory/internal/cgoalloc/allocator.go: pkg-config not supported: #cgo !windows pkg-config: arrow

~/code/github.com/braincorp/titanium-bazel rules_oci* ⇣⇡ 15s
❯ bazel run --noenable_bzlmod //:gazelle -- -build_tags=unit,integration,fts5,json1
INFO: Invocation ID: 43cb0b1b-a730-408c-ae97-b4040be17813
DEBUG: Rule 'bazel_gazelle' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c3323a4a7aed0427bae556d1953bb7852b3e0bcd755dc2f62229bf9b83bedf89"
DEBUG: Repository bazel_gazelle instantiated at:
  /home/tony.kinsley/code/github.com/braincorp/titanium-bazel/WORKSPACE:29:13: in <toplevel>
Repository rule http_archive defined at:
  /home/tony.kinsley/.cache/bazel/_bazel_tony.kinsley/5b466fe6d0bf121e0d4086ac6c4e9a68/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Analyzed target //:gazelle (152 packages loaded, 14843 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  /home/tony.kinsley/code/github.com/braincorp/titanium-bazel-build/bin/gazelle-runner.bash
  /home/tony.kinsley/code/github.com/braincorp/titanium-bazel-build/bin/gazelle
INFO: Elapsed time: 43.061s, Critical Path: 4.94s
INFO: 32 processes: 11 internal, 21 linux-sandbox.
INFO: Build completed successfully, 32 total actions
INFO: Running command line: /home/tony.kinsley/code/github.com/braincorp/titanium-bazel-build/bin/gazelle '-build_tags=unit,integration,fts5,json1'
gazelle: /home/tony.kinsley/code/github.com/braincorp/titanium-bazel/src/python/BUILD.bazel: unknown directive: gazelle:python_root
gazelle: /home/tony.kinsley/code/github.com/braincorp/titanium-bazel/vendor/github.com/apache/arrow/go/v11/arrow/memory/internal/cgoalloc/allocator.go: error reading go file: /home/tony.kinsley/code/github.com/braincorp/titanium-bazel/vendor/github.com/apache/arrow/go/v11/arrow/memory/internal/cgoalloc/allocator.go: pkg-config not supported: #cgo !windows pkg-config: arrow
gazelle: /home/tony.kinsley/code/github.com/braincorp/titanium-bazel/vendor/github.com/apache/arrow/go/v12/arrow/memory/internal/cgoalloc/allocator.go: error reading go file: /home/tony.kinsley/code/github.com/braincorp/titanium-bazel/vendor/github.com/apache/arrow/go/v12/arrow/memory/internal/cgoalloc/allocator.go: pkg-config not supported: #cgo !windows pkg-config: arrow
```

**Pull request merged**
