### PR TITLE
Use repo-relative labels everywhere

### PR DESCRIPTION
**Pull request by fmeum**
This makes it possible to load gazelle under any repo name, not
necessarily bazel_gazelle. This opens up the possibility to call the
gazelle Bazel module "gazelle".

### CODE REVIEW

**Review by achew22 — COMMENTED** [review]
Do we not need the checked in BUILD files any more?

**Comment by achew22** [comment]
> I dropped that commit out of an abundance of caution. I simply don't know, I couldn't find any reference outside of documentation. The tests passed locally with them deleted.

I think it's a good thing to do, but let's do it as a separate PR so that reversion is cleaner

**Comment by fmeum** [comment]
> > I dropped that commit out of an abundance of caution. I simply don't know, I couldn't find any reference outside of documentation. The tests passed locally with them deleted.
> 
> I think it's a good thing to do, but let's do it as a separate PR so that reversion is cleaner

Sounds good! The current PR should be good enough for bzlmod anyway.

**Review by linzhp — APPROVED** [review]
Successfully ran Gazelle with this patch in Uber's Go monorepo

**Pull request merged**
